# Application
spring.application.name=auth-service
server.port=8084

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/iam_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=YourSecretKeyHereMustBeAtLeast256BitsLongForHS256AlgorithmSecurity
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

# Logging
logging.level.com.bankmega.authservice=INFO
logging.level.org.springframework.security=DEBUG

app.username.superadmin=${USERNAME_SUPER_ADMIN:superadmin}
app.password.superadmin=${PASSWORD_SUPER_ADMIN:password}